#!/usr/bin/env bash
# dev-wt-ports.sh — Allocate worktree-isolated ports and write .wt-ports.env
#
# Usage (dual-mode):
#   Direct:   bash dev-wt-ports.sh <worktree-path> <branch>
#   gtr hook: WORKTREE_PATH=/path/to/wt BRANCH=feature/foo bash dev-wt-ports.sh
#
# Reads service port vars from .claude/dev-setup.json via _read_services().
# Allocates N consecutive free ports via dev-allocate-ports.sh, writes .wt-ports.env.
#
# Requires: bash 3.2+, node or jq, dev-allocate-ports.sh (sibling script)

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# Depth: tools/dev/ → 2 levels; scripts/ or bin/ → 1 level. Adapt on deploy.
PROJECT_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"

WORKTREE_PATH="${WORKTREE_PATH:-${1:-}}"
BRANCH="${BRANCH:-${2:-}}"

if [[ -z "$WORKTREE_PATH" || -z "$BRANCH" ]]; then
	echo "Usage: dev-wt-ports.sh <worktree-path> <branch>" >&2
	echo "       or set WORKTREE_PATH and BRANCH env vars (git gtr hook mode)" >&2
	exit 1
fi

PROJECT_DIR="$(cd "$PROJECT_ROOT" && pwd)"

_read_services() {
	local cfg="$PROJECT_DIR/.claude/dev-setup.json"
	if [[ ! -f "$cfg" ]]; then
		echo "ERROR: dev-setup.json not found: $cfg" >&2
		exit 1
	fi
	if command -v node &>/dev/null; then
		node -e "const c=require(process.argv[1]); Object.entries(c.services).forEach(([k,v])=>console.log(k+'='+v))" "$cfg"
	elif command -v jq &>/dev/null; then
		jq -r '.services | to_entries[] | .key + "=" + .value' "$cfg"
	else
		echo "ERROR: node or jq required to read dev-setup.json" >&2
		exit 1
	fi
}

# Collect port var names from services config (authoritative — no grep heuristic)
WT_VARS=()
while IFS= read -r _line; do
	[[ -z "$_line" ]] && continue
	_port_var="${_line%%=*}"
	WT_VARS+=("$_port_var")
done < <(_read_services)
N="${#WT_VARS[@]}"

if ((N == 0)); then
	echo "Warning: no services found in .claude/dev-setup.json — nothing to allocate" >&2
	exit 0
fi

# Allocate N consecutive free ports (space-separated on stdout)
PORTS_STR=$(bash "$SCRIPT_DIR/dev-allocate-ports.sh" "$N")
read -ra PORTS <<<"$PORTS_STR"

# Write .wt-ports.env in worktree root
OUT="$WORKTREE_PATH/.wt-ports.env"
{
	echo "# Generated by dev-wt-ports.sh — branch: $BRANCH"
	for i in "${!WT_VARS[@]}"; do
		echo "${WT_VARS[$i]}=${PORTS[$i]}"
	done
} >"$OUT"

# Print summary
summary=""
for i in "${!WT_VARS[@]}"; do
	summary+="${WT_VARS[$i]}=${PORTS[$i]} "
done
echo "Ports allocated for $BRANCH: ${summary% }"
